rules = [
  DisableSyntax,
  OrganizeImports,
  NoAutoTupling,
  RedundantSyntax
]

DisableSyntax {
  noReturns = true
  noFinalVal = true
}

OrganizeImports {
  targetDialect = Scala3
  removeUnused = true
  blankLines = Auto
  groups = [
    "re:(java|scala)\\.",
    "*"
  ]
}
