name: Build and Validate PRs to main

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  pr:
    uses: ./.github/workflows/build-validate-deploy-app.yml
    secrets: inherit
    with:
      validate: true
      deploy: false
